### ISSUE TITLE
convención en los commits

### ISSUE THREAD

**Issue by sanjorgek** [RGT91/legendary-barnacle#4]
podemos elegir en que idioma para que no parezca programado por pochos?

**Comment by RGT91** [comment]
Jajaja
Pues todo en español, ¿no?

**Comment by sanjorgek** [comment]
y tambien hice un push force así que tendrán conflictos al querer bajarlo
pero en este [link](https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files) dice como bajar los cambios cuando esto pase
tambien ya hable con @RGT91 para evitar que esto sea posible y así trabajar mejor

**Comment by robertocuc** [comment]
jajaja POCHOS.
Ok ahorita checo el link para ver qué onda.
Muchas gracias!!
